### ISSUE TITLE
Update to Pydantic 2.0?

### ISSUE THREAD

**Issue by eseglem** [eseglem/pycql2#40]
Consider updating to Pydantic 2.0

**Comment by Pierretls** [comment]
Hi, this could be fun. I tried on my side to make it pydantic v2 compatible but without success. I'm trapped with Accenti and Casei and I think it requires some expertise to fix it.

Regards

**Comment by eseglem** [comment]
Yeah, I have been meaning to come back to this. Just been spending my time on upgrading / using v2 in other things and haven't had the chance. 

They changed a bunch of stuff, like how Generics work. Does `class Accenti(BaseModel, Generic[E]):` not work?

**Comment by Pierretls** [comment]
Unfortunately no, tried a lot of things, include migration recommendations, but still have problems with these two generics  ! 

Test of filter42, this validation did not exist "as is". I suppose this is one part of the problem. 

![image](https://github.com/eseglem/pycql2/assets/52499749/c6d286f1-bd0f-4379-a65a-9b8e9e21c5e8)

If it helps !

**Comment by eseglem** [comment]
@Pierretls I think I managed to get it in the develop branch. Handling of Generics in Pydantic v2 is much more painful than it was before. Have to be explicit with the subclasses. Got inspiration from https://github.com/pydantic/pydantic/issues/8071 for how to eventually get there.

Have a few type ignores and stuff that deserve a bit more of a look, but got it passing tests. See: #60
